Repository fga-eps-mds/2023-1-Alectrion-EquipamentApi, pull requests merged in 2023-07, with the labels that each got.

#38 #148 FIX: Adiciona novo status de OS
  src/db/migrations/1685132702026-default.ts
  src/domain/entities/serviceOrderEnum/status.ts
  src/useCases/update-order-service/update-order-service.ts
  tests/update-order-service.spec.ts
Labels: EASY, FIX RELEASE

#42 Fix/tipo de equipamento
  src/repository/movementRepository.ts
  src/repository/order-service/list-order-service.ts
Labels: FIX RELEASE

#43 151 gerar relatorios de equipamentos 2
  src/repository/equipamentRepository.ts
  src/repository/protocol/equipmentRepositoryProtocol.ts
  src/useCases/getEquipment/getEquipmentUseCase.ts
Labels: MINOR RELEASE
