Repository fga-eps-mds/2023-1-Alectrion-EquipamentApi, pull requests merged in 2023-05, with the labels that each got.

#22 Develop
  src/db/entities/order-service.ts
  src/domain/entities/order-service.ts
  src/factories/controllers/update-equipment.ts
  src/factories/useCases/update-equipment-factory.ts
  src/factories/useCases/update-order-service-factory.ts
  src/presentation/controller/update-equipment-controller.ts
  src/repository/equipment/update-equipment.ts
  src/routes.ts
  src/useCases/updateEquipment/updateEquipment.ts
  tests/update-equipment.spec.ts
Labels: MINOR RELEASE

#24 Develop
  package.json
  src/factories/controllers/deleteEquipment.ts
  src/factories/useCases/deleteEquipment.ts
  src/middlewares/admin-auth-middleware.ts
  src/presentation/controller/deleteEquipmentController.ts
  src/presentation/controller/deleteMovementController.ts
  src/presentation/helpers/http.ts
  src/repository/equipamentRepository.ts
  src/repository/protocol/equipmentRepositoryProtocol.ts
  src/repository/protocol/unitRepositoryProtocol.ts
  src/repository/unitRepository.ts
  src/routes.ts
  src/useCases/createEquipment/createEquipmentUseCase.ts
  src/useCases/createMovement/createMovementUseCase.ts
  src/useCases/deleteEquipment/deleteEquipmentUseCase.ts
  tests/create-equipment-usecase.spec.ts
  tests/createMovementUseCase.spec.ts
  tests/deleteEquipmentController.spec.ts
  tests/deleteEquipmentUseCase.spec.ts
  tests/deleteMovementController.spec.ts
  yarn.lock
Labels: MINOR RELEASE

#25 84 filtro de busca equipamentos
  src/domain/entities/equipamentEnum/status.ts
  src/presentation/controller/getEquipmentController.ts
  src/repository/equipamentRepository.ts
  src/repository/protocol/equipmentRepositoryProtocol.ts
Labels: MINOR RELEASE

#23 81 - Adicionar Filtros de Movimentação
  src/repository/movementRepository.ts
  src/repository/protocol/movementRepositoryProtocol.ts
  src/useCases/findMovements/findMovementsUseCase.ts
  tests/findMovementsController.spec.ts
  tests/findMovementsUseCase.spec.ts
Labels: FEATURE, MEDIUM, EPS, MDS, MINOR RELEASE

#27 FIX: Aumento de Cobertura
  tests/create-order-service.spec.ts
Labels: HOTFIX, EPS

#28 FIX: Desfeita Alteração no Teste
  sonar-project.properties
  src/db/entities/equipment.ts
  src/domain/entities/equipment.ts
  src/repository/equipamentRepository.ts
  src/useCases/getEquipment/getEquipmentUseCase.ts
  tests/create-order-service.spec.ts
  tests/errors/create-order-service.spec.ts
Labels: HOTFIX, EPS, MAJOR RELEASE
